### ISSUE TITLE
bootbot-cli workflow doubt!

### ISSUE THREAD

**Issue by brenohq** [Charca/bootbot-cli#2]
Hello, I am a beginner in chatbots development and a friend recommended me the [bootbot](https://github.com/Charca/bootbot) framework, I really liked it! I also found this CLI, but I am in doubt about how I will develop using it.

Should I run **bootbot start** every time I change a file?
Should I run **bootbot start** together with **nodemon index.js**?
Should I set up my webhook URLs every time I start developing?

I wanted a way to observe real-time changes while developing, could anyone help me?

And congratulations for the brilliant work! @Charca

**Comment by Charca** [comment]
Replied here: https://github.com/Charca/bootbot/issues/21
